VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICommand"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "StowagePlan.api"
Option Explicit

Public Sub InitiateProperties(ByRef manager As IManager, ByVal control As IRibbonControl)
End Sub

Sub Execute(ParamArray args() As Variant)
End Sub

